In [3]:
import json
import pandas as pd
with open("Raw_Data/acndata_sessions (1).json", "r") as f:
    data = json.load(f)

In [4]:
data.keys()

dict_keys(['_meta', '_items'])

In [5]:
sessions = data["_items"]

In [6]:
df = pd.DataFrame(sessions)

In [7]:
df.head()

,_id,clusterID,connectionTime,disconnectTime,doneChargingTime,kWhDelivered,sessionID,siteID,spaceID,stationID,timezone,userID,userInputs
0,5c46721ff9af8b2d64cb23f4,0039,"Sat, 05 Jan 2019 15:51:36 GMT","Sat, 05 Jan 2019 17:34:35 GMT","Sat, 05 Jan 2019 17:34:32 GMT",7.808,2_39_139_28_2019-01-05 15:51:36.017459,0002,CA-303,2-39-139-28,America/Los_Angeles,000000675,"[{'WhPerMile': 313, 'kWhRequested': 9.39, 'mil..."
1,5c46721ff9af8b2d64cb23f5,0039,"Sat, 05 Jan 2019 16:00:45 GMT","Sat, 05 Jan 2019 23:11:16 GMT","Sat, 05 Jan 2019 23:11:11 GMT",5.121,2_39_79_379_2019-01-05 16:00:44.984489,0002,CA-327,2-39-79-379,America/Los_Angeles,000001083,"[{'WhPerMile': 400, 'kWhRequested': 8.0, 'mile..."
2,5c46721ff9af8b2d64cb23f6,0039,"Sat, 05 Jan 2019 17:26:48 GMT","Sat, 05 Jan 2019 19:16:48 GMT","Sat, 05 Jan 2019 18:24:19 GMT",0.845,2_39_125_21_2019-01-05 17:26:48.040576,0002,CA-311,2-39-125-21,America/Los_Angeles,NaN,None
3,5c46721ff9af8b2d64cb23f7,0039,"Sat, 05 Jan 2019 18:13:42 GMT","Sat, 05 Jan 2019 20:10:21 GMT","Sat, 05 Jan 2019 19:52:09 GMT",4.504,2_39_91_437_2019-01-05 18:13:42.492305,0002,CA-317,2-39-91-437,America/Los_Angeles,000000743,"[{'WhPerMile': 400, 'kWhRequested': 8.0, 'mile..."
4,5c46721ff9af8b2d64cb23f8,0039,"Sat, 05 Jan 2019 18:20:28 GMT","Sat, 05 Jan 2019 20:12:15 GMT","Sat, 05 Jan 2019 19:32:17 GMT",2.981,2_39_138_29_2019-01-05 18:20:28.266831,0002,CA-304,2-39-138-29,America/Los_Angeles,000000891,"[{'WhPerMile': 300, 'kWhRequested': 6.0, 'mile..."

In [8]:
df.shape

(11, 13)

In [9]:
df.columns

Index(['_id', 'clusterID', 'connectionTime', 'disconnectTime',
       'doneChargingTime', 'kWhDelivered', 'sessionID', 'siteID', 'spaceID',
       'stationID', 'timezone', 'userID', 'userInputs'],
      dtype='str')

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   _id               11 non-null     str
 1   clusterID         11 non-null     str
 2   connectionTime    11 non-null     str
 3   disconnectTime    11 non-null     str
 4   doneChargingTime  11 non-null     str
 5   kWhDelivered      11 non-null     float64
 6   sessionID         11 non-null     str
 7   siteID            11 non-null     str
 8   spaceID           11 non-null     str
 9   stationID         11 non-null     str
 10  timezone          11 non-null     str
 11  userID            10 non-null     str
 12  userInputs        10 non-null     object
dtypes: float64(1), object(1), str(11)
memory usage: 3.4+ KB

In [11]:
df.isnull().sum()

_id                 0
clusterID           0
connectionTime      0
disconnectTime      0
doneChargingTime    0
kWhDelivered        0
sessionID           0
siteID              0
spaceID             0
stationID           0
timezone            0
userID              1
userInputs          1
dtype: int64

In [13]:
df.duplicated().sum()

TypeError: unhashable type: 'list'

In [14]:
df["sessionID"].duplicated().sum()

np.int64(0)

In [17]:
df["connectionTime"] = pd.to_datetime(df["connectionTime"])
df["disconnectTime"] = pd.to_datetime(df["disconnectTime"])
df["doneChargingTime"] = pd.to_datetime(df["doneChargingTime"])

In [18]:
df["charging_duration_minutes"] = (
    df["disconnectTime"] - df["connectionTime"]
).dt.total_seconds() / 60

In [19]:
df[["connectionTime", "disconnectTime", "charging_duration_minutes"]]

        connectionTime      disconnectTime  charging_duration_minutes
0  2019-01-05 15:51:36 2019-01-05 17:34:35                 102.983333
1  2019-01-05 16:00:45 2019-01-05 23:11:16                 430.516667
2  2019-01-05 17:26:48 2019-01-05 19:16:48                 110.000000
3  2019-01-05 18:13:42 2019-01-05 20:10:21                 116.650000
4  2019-01-05 18:20:28 2019-01-05 20:12:15                 111.783333
5  2019-01-05 18:36:04 2019-01-05 19:23:29                  47.416667
6  2019-01-05 18:54:43 2019-01-05 20:29:33                  94.833333
7  2019-01-05 19:25:45 2019-01-05 22:23:11                 177.433333
8  2019-01-05 19:37:49 2019-01-06 00:20:09                 282.333333
9  2019-01-05 20:35:47 2019-01-05 22:14:44                  98.950000
10 2019-01-05 20:43:26 2019-01-05 22:07:45                  84.316667

In [20]:
df["kWhDelivered"].describe()

count    11.000000
mean      5.768909
std       4.037533
min       0.845000
25%       3.607000
50%       5.121000
75%       6.629500
max      15.672000
Name: kWhDelivered, dtype: float64

In [21]:
df[df["kWhDelivered"] < 0]

Empty DataFrame
Columns: [_id, clusterID, connectionTime, disconnectTime, doneChargingTime, kWhDelivered, sessionID, siteID, spaceID, stationID, timezone, userID, userInputs, charging_duration_minutes]
Index: []

In [22]:
df["kWhDelivered"].sort_values()

2      0.845
5      2.308
4      2.981
10     4.233
3      4.504
1      5.121
9      5.290
6      5.451
0      7.808
7      9.245
8     15.672
Name: kWhDelivered, dtype: float64

In [23]:
df.describe()

,connectionTime,disconnectTime,doneChargingTime,kWhDelivered,charging_duration_minutes
count,11,11,11,11.000000,11.000000
mean,2019-01-05 18:31:32.090909,2019-01-05 21:02:11.454545,2019-01-05 20:45:37.363636,5.768909,150.656061
min,2019-01-05 15:51:36,2019-01-05 17:34:35,2019-01-05 17:34:32,0.845000,47.416667
25%,2019-01-05 17:50:15,2019-01-05 19:46:55,2019-01-05 19:27:49.500000,3.607000,96.891667
50%,2019-01-05 18:36:04,2019-01-05 20:29:33,2019-01-05 20:08:12,5.121000,110.000000
75%,2019-01-05 19:31:47,2019-01-05 22:18:57.500000,2019-01-05 22:15:24,6.629500,147.041667
max,2019-01-05 20:43:26,2019-01-06 00:20:09,2019-01-06 00:16:44,15.672000,430.516667
std,NaN,NaN,NaN,4.037533,111.274423

In [24]:
df["charging_duration_minutes"].describe()

count     11.000000
mean     150.656061
std      111.274423
min       47.416667
25%       96.891667
50%      110.000000
75%      147.041667
max      430.516667
Name: charging_duration_minutes, dtype: float64

In [25]:
df.to_csv("Cleaned_Data/charging_sessions_clean.csv", index=False)

In [26]:
df.to_csv("Cleaned_Data/charging_sessions_clean.csv", index=False)

print("Rows:", len(df))
print("Columns:", len(df.columns))

Rows: 11
Columns: 14

In [27]:
df.columns.tolist()

['_id',
 'clusterID',
 'connectionTime',
 'disconnectTime',
 'doneChargingTime',
 'kWhDelivered',
 'sessionID',
 'siteID',
 'spaceID',
 'stationID',
 'timezone',
 'userID',
 'userInputs',
 'charging_duration_minutes']

In [28]:
import json

df["userInputs"] = df["userInputs"].apply(
    lambda x: json.dumps(x) if isinstance(x, (dict, list)) else None
)

In [29]:
print(df["userInputs"].iloc[0])

[{"WhPerMile": 313, "kWhRequested": 9.39, "milesRequested": 30, "minutesAvailable": 149, "modifiedAt": "Sat, 05 Jan 2019 15:52:16 GMT", "paymentRequired": true, "requestedDeparture": "Sat, 05 Jan 2019 18:20:36 GMT", "userID": 675}]

In [30]:
df.to_csv(
    "Cleaned_Data/charging_sessions_clean.csv",
    index=False
)